### ISSUE TITLE
I crashed yaqlator.com

### ISSUE THREAD

**Issue by punkrokk** [ALU-CloudBand/yaqluator#2]
Hi there - I pasted a pretty big json string and crashed your website. Any chance you can reset it? @MosheElisha

**Comment by mjtice** [comment]
lol, I thought it was me and my nasty json string...

**Comment by punkrokk** [comment]
Happy to transfer the blame

**Comment by MosheElisha** [comment]
Hi,

Thanks a lot for reporting. The server is recovered now. 
I will work to improve that so it won't crash :-)

@punkrokk can you please provide here the JSON and the steps to reproduce?

Thanks!

**Comment by punkrokk** [comment]
Thanks!

Cheers,

JP

**Comment by punkrokk** [comment]
> Hi,
> 
> Thanks a lot for reporting. The server is recovered now.
> I will work to improve that so it won't crash :-)
> 
> @punkrokk can you please provide here the JSON and the steps to reproduce?
> 
> Thanks!

@MosheElisha I can send it somewhere private... or DM you a link on twitter..

**Comment by punkrokk** [comment]
bump: @MosheElisha I can send it somewhere private... or DM you a link on twitter..

**Comment by MosheElisha** [comment]
> bump: @MosheElisha I can send it somewhere private... or DM you a link on twitter..

I tried to contact you on Twitter but it was blocked. Anyway, I believe I know how to reproduce. Now I only need some time to fix :-)

I'll let you know if I need anything else. 

Thanks a lot!

**Comment by nzlosh** [comment]
I'm not sure if this is related to the fix, but yaqlulator.com is completely unusable at the moment.  I attempted to evaluate an expression of `$` on a json structure which consists of 59 lines and 1895 characters and am getting `Forbidden` with no evaluation returned.

**Comment by punkrokk** [comment]
@MosheElisha Follow me @jp_bourget on twitter :)

**Comment by MosheElisha** [comment]
@nzlosh Sorry about that. The security rules were too strict for a short period. It should be OK now.

@punkrokk I am following you :-)
